lifting_options:                            
  Building:
    height_roof: percentile-90
    height_floor: percentile-10
    lod: 1
    triangulate: true
    floor: false
    inner_walls: false
  Water:
    height: percentile-10
  Road:
    height: percentile-50
    filter_outliers: true
    flatten: true
  Separation:
    height: percentile-80
  Bridge/Overpass:
    height: percentile-50
    flatten: true
  Terrain:                      # Terrain is percentile-50
    simplification: 0
    simplification_tinsimp: 0.0
    inner_buffer: 0.0
  Forest:                       # Forest is percentile-50
    simplification: 0
    simplification_tinsimp: 0.0
    inner_buffer: 0.0

input_elevation:
  - datasets:
      - points.laz
    omit_LAS_classes:
      - 1 # unclassified
    thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5