---
version: 1.1
title: 3dfier
description: Build 3D models from your surroundings with watertight results for simulation and visualisation.
show_downloads: true
github_username:  tudelft3d
twitter username: tudelft3d
logo: img/3dfierLogo.png

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
